### ISSUE TITLE
error running with PyU4V 3.0.0.8.

### ISSUE THREAD

**Issue by airxpress** [stevenctong/vmax_monitoring#1]
Hello.  First off thanks for creating this.  I'm wondering if you could assist me with this error I'm receiving below.  It does actually gather the data and insert it into my InfluxDB but then it errors out and doesnt continue to gather alerting and SRP details.  I've tried to troubleshoot myself and change some stuff around to no avail.  Any help would be appreciated.  Using PyU4V 3.0.0.8.

File "./vmax_monitoring.py", line 210, in <module>
    main()
  File "./vmax_monitoring.py", line 129, in main
    end_date)
  File "/usr/lib/python2.7/site-packages/PyU4V/performance.py", line 545, in get_host_metrics
    host_results['perf_data'] = host_perf_data[0]['resultList']['result']

**Comment by airxpress** [comment]
Looks to be due to some hosts that don't have any performance data so its not returning anything and errors out.  So not an issue with this script, more of the way the PyU4V performance.py is handling it.

**Comment by Posterminal** [comment]
how did you get around this problem @airxpress ? my decision to comment on the following lines: 
host_list = ru.provisioning.get_host_list()
 for host_id in host_list:
 host_metrics = ru.performance.get_host_metrics(host_id, start_date, \
  end_date)
  insert_metrics(dbclient, host_metrics, "Host", {"Host" : host_id})
